# Generated by Django 5.0.6 on 2024-07-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transactions_bankrupt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='bankrupt',
        ),
    ]
