# Generated by Django 5.0.7 on 2024-07-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=250)),
                ('car_price', models.IntegerField()),
                ('car_brand', models.CharField(max_length=100)),
                ('car_milage', models.IntegerField()),
                ('car_location', models.CharField(max_length=150)),
                ('car_description', models.TextField()),
            ],
        ),
    ]
