# Generated by Django 5.0.7 on 2024-07-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_addcarmodel_car_image1_addcarmodel_car_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_image1',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images/'),
        ),
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_image2',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images/'),
        ),
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_image3',
            field=models.ImageField(blank=True, null=True, upload_to='cars_images/'),
        ),
    ]
