# Generated by Django 5.0.7 on 2024-07-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_addcarmodel_car_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcarmodel',
            name='car_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
