# Generated by Django 5.0.7 on 2024-07-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_commentmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcarmodel',
            name='car_vin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
