# Generated by Django 5.0.7 on 2024-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_addcarmodel_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_status',
            field=models.CharField(blank=True, choices=[('stock', 'In Stock'), ('out', 'Out Of Stock')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_type',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=5, null=True),
        ),
    ]
