# Generated by Django 5.0.7 on 2024-07-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_alter_addcarmodel_car_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_status',
            field=models.CharField(blank=True, choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used')], max_length=5, null=True),
        ),
    ]
