# Generated by Django 5.0.7 on 2024-07-12 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('cars', '0014_alter_commentmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcarmodel',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brands.brandmodel'),
        ),
    ]
