# Generated by Django 5.0.6 on 2024-06-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150)),
                ('post_content', models.TextField()),
                ('category', models.CharField(choices=[('M', 'Medium'), ('L', 'Large'), ('S', 'Small')], max_length=1)),
            ],
        ),
    ]
