# Generated by Django 5.0.6 on 2024-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('P', 'Programming'), ('J', 'Java'), ('H', 'Horror'), ('C', 'C'), ('C++', 'C++'), ('JS', 'JavaScript')], max_length=50),
        ),
    ]
