# Generated by Django 5.0.6 on 2024-06-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('C', 'C'), ('J', 'Java'), ('C++', 'C++'), ('P', 'Programming'), ('H', 'Horror'), ('JS', 'JavaScript')], max_length=50),
        ),
    ]
