# Generated by Django 5.0.6 on 2024-06-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('H', 'Horror'), ('J', 'Java'), ('JS', 'JavaScript'), ('C', 'C'), ('P', 'Programming'), ('C++', 'C++')], max_length=50),
        ),
    ]
