# Generated by Django 5.0.6 on 2024-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactions_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='bankrupt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Loan'), (4, 'Loan Paid'), (5, 'Send Money')], null=True),
        ),
    ]
