# Generated by Django 5.0.6 on 2024-07-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.IntegerField(choices=[('M', 'Medium'), ('S', 'Small'), ('L', 'Large')], max_length=10),
        ),
    ]
