# Generated by Django 5.0.6 on 2024-07-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_postmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.IntegerField(choices=[('L', 'Large'), ('S', 'Small'), ('M', 'Medium')]),
        ),
    ]
