# Generated by Django 5.0.6 on 2024-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_author_postmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('M', 'Medium'), ('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
    ]
