# Generated by Django 5.0.6 on 2024-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
