# Generated by Django 5.0.6 on 2024-06-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('profiles', '0002_profiles_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='ProfilesModel',
        ),
    ]
