# Generated by Django 5.0.6 on 2024-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_student_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.TextField(default='Rahim'),
        ),
    ]
